language: ruby
sudo: false
cache: bundler
rvm:
  - 2.0
  - 2.1
  - 2.2
  - 2.3
  - 2.4
  - 2.5
  - 2.6
  - 2.7
  - jruby-head
matrix:
  allow_failures:
    - rvm: jruby-head
env:
  - 'RSPEC_OPTIONS="--tag ~slow spec"'
  - 'RSPEC_OPTIONS="--tag slow spec/bidi/bidi_spec.rb spec/collation/collation_spec.rb"'
  - 'RSPEC_OPTIONS="--tag slow spec/collation/tailoring_spec.rb spec/collation/trie_dumps_spec.rb"'
  - 'RSPEC_OPTIONS="--tag slow spec/formatters/numbers/rbnf/rbnf_spec.rb spec/timezones/timezone_spec.rb"'
script: 'bundle exec rspec $RSPEC_OPTIONS'
